name = "pant-growth-engine"
pages_build_output_dir = "dist"
compatibility_date = "2024-07-25"

[[d1_databases]]
binding = "DB" # Nome que o código usará para acessar o banco
database_name = "pant-growth-database"
database_id = "d590a31b-1232-4e46-a5d6-579dfbd9e1a1"